# Author: Juniper Networks
# Contact: SAVITHRU AT ICLOUD DOT COM
# Copyright (c) 2018 Juniper Networks, Inc. All rights reserved
# Tier1 Database Tier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    tier: db
    application: HRApp
    site: USA
    deployment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: db
  template:
    metadata:
      labels:
        tier: db
    spec:
      containers:
        - name: database-pod
          image: savvythru/three-tier-database
          env:
            - name: MYSQL_DATABASE
              value: redmine
            - name: MYSQL_ROOT_PASSWORD
              value: secret
---
apiVersion: v1
kind: Service
metadata:
  name: database-svc
  labels:
    tier: db
    application: HRApp
    site: USA
    deployment: production
spec:
  selector:
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-db-port-3306-only
spec:
  podSelector:
    matchLabels:
      tier: db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: app
    ports:
    - protocol: TCP
      port: 3306
# Tier2 - App Tier 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    tier: app
    application: HRApp
    site: USA
    deployment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: app
  template:
    metadata:
      labels:
        tier: app
    spec:
      containers:
        - name: frontend-pod
          image: savvythru/three-tier-frontend
          env:
            - name: REDMINE_DB_MYSQL
              value: database-svc
            - name: REDMINE_DB_PASSWORD
              value: secret
---
apiVersion: v1
kind: Service
metadata:
  name: redmine-svc
  labels:
    tier: app
    application: HRApp
    site: USA
    deployment: production
spec:
  selector:
    tier: app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-app-port-3000-only
spec:
  podSelector:
    matchLabels:
      tier: app
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: web
    ports:
    - protocol: TCP
      port: 3000
#Tier 3 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-pod
  labels:
    tier: web
    application: HRApp
    site: USA
    deployment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: web
  template:
    metadata:
      labels:
        tier: web
    spec:
      containers:
        - name: proxy-pod
          image: savvythru/three-tier-proxy
          env:
            - name: REDMINE_SVC
              value: redmine-svc
            - name: REDMINE_SVC_PORT
              value: "3000"
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-svc
  labels:
    tier: web
    application: HRApp
    site: USA
    deployment: production
spec:
  selector:
    tier: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
